### ISSUE TITLE
error creating the trigger

### ISSUE THREAD

**Issue by AsaNadeau** [sailyapp/aws-s3-lambda-thumbnail-generator#4]
getting this error:  

"There was an error creating the trigger: Your bucket must be in the same region as the function."

My S3 is global, but Global isn't an option for Lambda.

**Comment by sailyapp** [comment]
That's true. Lambda is still not available in all regions, so you'll have to make sure your S3 bucket falls within the same region.

**Comment by AsaNadeau** [comment]
ok got it working by adjusting lambda to use same region...thanks!
